export const products = [
  {
    id: "1",
    name: "White Raha T-shirt",
    price: "1,000",
    image: require("./assets/test-merch.png"),
  },
  {
    id: "2",
    name: "Black Raha T-shirt",
    price: "1,200",
    image: require("./assets/test-merch-2.png"),
  },
  {
    id: "3",
    name: "Black Raha Trouser",
    price: "3,000",
    image: require("./assets/test-merch-3.png"),
  },
  {
    id: "4",
    name: "Black Raha Office Pants",
    price: "2,500",
    image: require("./assets/test-merch-4.png"),
  },
  {
    id: "5",
    name: "Grey Raha Sweatpants",
    price: "1,500",
    image: require("./assets/test-merch-5.png"),
  },
  {
    id: "6",
    name: "Yellow Raha T-shirt",
    price: "1,000",
    image: require("./assets/test-merch-6.png"),
  },
];

export const DealData = [
  {
    id: "1",
    image: require("./assets/logo.png"),
    name: "Raha Rave",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Early Bird",
    oldPrice: "2,000",
    newPrice: "1,000",
  },
  {
    id: "2",
    image: require("./assets/logo.png"),
    name: "Raha Rave",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "3",
    image: require("./assets/logo.png"),
    name: "Raha December",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Early Bird",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "4",
    image: require("./assets/logo.png"),
    name: "Raha December",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "5",
    image: require("./assets/logo.png"),
    name: "Raha Rave",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "7",
    image: require("./assets/logo.png"),
    name: "Raha December",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "8",
    image: require("./assets/logo.png"),
    name: "Raha December",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "9",
    image: require("./assets/logo.png"),
    name: "Raha December",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
];
