export const products = [
  {
    id: "1",
    name: "Raha T-shirt",
    price: "1,000",
    image: require("../../../assets/test-merch.png"),
  },
  {
    id: "2",
    name: "Raha Polo Shirt",
    price: "1,500",
    image: require("../../../assets/test-merch-2.png"),
  },
  {
    id: "3",
    name: "Raha Hoodie",
    price: "3,000",
    image: require("../../../assets/test-merch-3.png"),
  },
  {
    id: "4",
    name: "Raha T-shirt",
    price: "1,000",
    image: require("../../../assets/test-merch.png"),
  },
  {
    id: "5",
    name: "Raha Polo Shirt",
    price: "1,500",
    image: require("../../../assets/test-merch-2.png"),
  },
  {
    id: "6",
    name: "Raha Hoodie",
    price: "3,000",
    image: require("../../../assets/test-merch-3.png"),
  },
];

export const DealData = [
  {
    id: "1",
    image: require("../../../assets/davido-head.jpeg"),
    name: "Raha Rave",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Early Bird",
    oldPrice: "2,000",
    newPrice: "1,000",
  },
  {
    id: "2",
    image: require("../../../assets/kingpromise.jpeg"),
    name: "Raha Rave",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "3",
    image: require("../../../assets/davido-head.jpeg"),
    name: "Raha December",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Early Bird",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "4",
    image: require("../../../assets/kingpromise.jpeg"),
    name: "Raha December",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "5",
    image: require("../../../assets/davido-head.jpeg"),
    name: "Raha Rave",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
  {
    id: "6",
    image: require("../../../assets/kingpromise.jpeg"),
    name: "Raha December",
    time: "4:00pm - 10:00pm",
    location: "Sarit Expo Center",
    discount: "50%",
    ticketType: "Advance",
    oldPrice: "2,500",
    newPrice: "1,250",
  },
];
